FROM nginx:latest

COPY index.html /usr/share/nginx/html/
COPY six.css /usr/share/nginx/html/
COPY americano-image.png /usr/share/nginx/html/
COPY cappuccino-image.png /usr/share/nginx/html/
COPY coffee.png /usr/share/nginx/html/
COPY csimg.jpeg /usr/share/nginx/html/
COPY latte-image.png /usr/share/nginx/html/
COPY cappuccino.png /usr/share/nginx/html/
COPY mocha.png /usr/share/nginx/html/
COPY mocha-image.png /usr/share/nginx/html

EXPOSE 80

