apiVersion: apps/v1
kind: Deployment
metadata:
  name: siri-go-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
        app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app
        image: registry.gitlab.com/devops8093803/project4:arm64
        imagePullPolicy: "Always"
      imagePullSecrets:
      - name: siri-flask-app-secret
---

apiVersion: v1
kind: Service
metadata:
  name: siri-go-app-service
spec:
  selector:
    app: go-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30057
  type: NodePort